[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.28"

optimizer = true
optimizer_runs = 10000

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
